# .github/actions/setup-aws-tf-cache/action.yml

name: Setup AWS OIDC and Terraform Cache
description: Configures AWS credentials, verifies identity, checks out repo, and sets up Terraform plugin cache.
inputs:
  aws-role-arn:
    description: The ARN of the AWS role to assume
    required: true
  aws-region:
    description: The AWS region to use
    required: true
  cache-path:
    description: The path to the Terraform plugin cache directory
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - name: Verify IAM Role Assumption
      run: aws sts get-caller-identity
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Terraform Plugin Cache Dir
      run: mkdir -p ${{ inputs.cache-path }}
      shell: bash

    - name: Terraform Plugin Cache
      uses: actions/cache@v4.2.3
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ runner.os }}-terraform-plugin-cache-${{ hashFiles('**/.terraform.lock.hcl') }}
